export const orders_data = {
    "data": {
        "currentPage": 0,
        "pageSize": 0,
        "lastPage": 0,
        "total": 10,
        "data": [
            {
                "id": 7,
                "orderUuid": "fgdfdffdg",
                "unitPrice": null,
                "count": null,
                "totalPrice": null,
                "userName": "dasd",
                "showUrl": null,
                "goodsName": "string",
                "orderStatus": null,
                "msgType": null,
                "msg": null
            },
            {
                "id": 11,
                "orderUuid": "ddfsdf",
                "unitPrice": null,
                "count": null,
                "totalPrice": null,
                "userName": "fasd",
                "showUrl": null,
                "goodsName": "fds",
                "orderStatus": null,
                "msgType": null,
                "msg": null
            },
            {
                "id": 12,
                "orderUuid": "fasds",
                "unitPrice": null,
                "count": null,
                "totalPrice": null,
                "userName": "dasd",
                "showUrl": null,
                "goodsName": "fds",
                "orderStatus": null,
                "msgType": null,
                "msg": null
            },
            {
                "id": 13,
                "orderUuid": "fsfasdasd",
                "unitPrice": null,
                "count": null,
                "totalPrice": null,
                "userName": "change_money",
                "showUrl": null,
                "goodsName": null,
                "orderStatus": null,
                "msgType": null,
                "msg": null
            },
            {
                "id": 3,
                "orderUuid": "8e9a3280-76d9-4f2b-b804-9e59508c4024",
                "unitPrice": null,
                "count": 2,
                "totalPrice": null,
                "userName": "change_money",
                "showUrl": null,
                "goodsName": "string",
                "orderStatus": 1,
                "msgType": 1,
                "msg": "备注"
            },
            {
                "id": 4,
                "orderUuid": "be20413f-4899-47f6-843f-1c41b4761da5",
                "unitPrice": null,
                "count": 2,
                "totalPrice": null,
                "userName": "change_money",
                "showUrl": null,
                "goodsName": "string",
                "orderStatus": 1,
                "msgType": 1,
                "msg": "备注"
            },
            {
                "id": 5,
                "orderUuid": "846531dc-56c6-4c26-9b6c-67b7451d4658",
                "unitPrice": 20,
                "count": 2,
                "totalPrice": 40,
                "userName": "change_money",
                "showUrl": null,
                "goodsName": "string",
                "orderStatus": 1,
                "msgType": 1,
                "msg": "备注"
            },
            {
                "id": 6,
                "orderUuid": "sadasasd",
                "unitPrice": null,
                "count": null,
                "totalPrice": null,
                "userName": "dasd",
                "showUrl": "http://",
                "goodsName": "修改",
                "orderStatus": 1,
                "msgType": null,
                "msg": null
            },
            {
                "id": 8,
                "orderUuid": "sdfsdfsf",
                "unitPrice": null,
                "count": null,
                "totalPrice": null,
                "userName": "fasd",
                "showUrl": null,
                "goodsName": "string",
                "orderStatus": 1,
                "msgType": null,
                "msg": null
            },
            {
                "id": 1,
                "orderUuid": "123123",
                "unitPrice": 20.2,
                "count": 3,
                "totalPrice": 60.6,
                "userName": "change_money",
                "showUrl": null,
                "goodsName": "string",
                "orderStatus": 2,
                "msgType": null,
                "msg": null
            }
        ]
    },
    "code": 200,
    "description": "操作成功"
}